### ISSUE TITLE
function is UndefinedClass?

### ISSUE THREAD

**Issue by elcuervo** [nu7hatch/mustang#1]
Just curiosity..

```
require "mustang"

c = Mustang::Context.new
e = c.eval "function a(){}"

puts e.class
# => V8::UndefinedClass
```

**Comment by nu7hatch** [comment]
Yeap, it's correct. On function declaration V8 returns `undefined`, but when you evaluate:

```
f = c.eval "function a(){}; a;"
puts f.class
# => V8::Function
```

**Comment by elcuervo** [comment]
Yeah, i noticed that, just curious about the other

## 

Bruno Aguirre
brunoaguirre.com

**Comment by nu7hatch** [comment]
It happens because function is specific kind of declaration. When you run it in chrome console it will acts the same
